[Metadata]
Skin name=DESKTOP VU-METER
Version=2.0
Information=SOUND LEVEL
Author=HiTBiT-PA
Website=http://hitbit-pa.deviantart.com/
License=Creative Commons Attribution-Noncommercial-Share Alike 3.0 License

[MeasureAudioOutput]
Measure=Plugin
Plugin=AudioLevel
Port=#vPort#
RMSAttack=#vRMSAttack#
RMSDecay=#vRMSDecay#
RMSGain=#vRMSGain#
PeakAttack=#vPeakAttack#
PeakDecay=#vPeakDecay#
PeakGain=#vPeakGain#
FFTSize=#vFFTSize#
FFTOverlap=#vFFTOverlap#
FFTAttack=#vFFTAttack#
FFTDecay=#vFFTDecay#
FreqMin=#vFreqMin#
FreqMax=#vFreqMax#
Sensitivity=#vSensitivity#
Bands=24

[MeasureFFT_L_00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=0
InvertMeasure=0

[MeasureFFT_L_01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=1
InvertMeasure=0

[MeasureFFT_L_02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=2
InvertMeasure=0

[MeasureFFT_L_03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=3
InvertMeasure=0

[MeasureFFT_L_04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=4
InvertMeasure=0

[MeasureFFT_L_05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=5
InvertMeasure=0

[MeasureFFT_L_06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=6
InvertMeasure=0

[MeasureFFT_L_07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=7
InvertMeasure=0

[MeasureFFT_L_08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=8
InvertMeasure=0

[MeasureFFT_L_09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=9
InvertMeasure=0

[MeasureFFT_L_10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=10
InvertMeasure=0

[MeasureFFT_L_11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=11
InvertMeasure=0

[MeasureFFT_L_12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=12
InvertMeasure=0

[MeasureFFT_L_13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=13
InvertMeasure=0

[MeasureFFT_L_14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=14
InvertMeasure=0

[MeasureFFT_L_15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=15
InvertMeasure=0

[MeasureFFT_L_16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=16
InvertMeasure=0

[MeasureFFT_L_17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=17
InvertMeasure=0

[MeasureFFT_L_18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=18
InvertMeasure=0

[MeasureFFT_L_19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=19
InvertMeasure=0

[MeasureFFT_L_20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=20
InvertMeasure=0

[MeasureFFT_L_21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=21
InvertMeasure=0

[MeasureFFT_L_22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=22
InvertMeasure=0

[MeasureFFT_L_23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=L
Type=Band
BandIdx=23
InvertMeasure=0

[MeasureFFT_R_00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=0
InvertMeasure=0

[MeasureFFT_R_01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=1
InvertMeasure=0

[MeasureFFT_R_02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=2
InvertMeasure=0

[MeasureFFT_R_03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=3
InvertMeasure=0

[MeasureFFT_R_04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=4
InvertMeasure=0

[MeasureFFT_R_05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=5
InvertMeasure=0

[MeasureFFT_R_06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=6
InvertMeasure=0

[MeasureFFT_R_07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=7
InvertMeasure=0

[MeasureFFT_R_08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=8
InvertMeasure=0

[MeasureFFT_R_09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=9
InvertMeasure=0

[MeasureFFT_R_10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=10
InvertMeasure=0

[MeasureFFT_R_11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=11
InvertMeasure=0

[MeasureFFT_R_12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=12
InvertMeasure=0

[MeasureFFT_R_13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=13
InvertMeasure=0

[MeasureFFT_R_14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=14
InvertMeasure=0

[MeasureFFT_R_15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=15
InvertMeasure=0

[MeasureFFT_R_16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=16
InvertMeasure=0

[MeasureFFT_R_17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=17
InvertMeasure=0

[MeasureFFT_R_18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=18
InvertMeasure=0

[MeasureFFT_R_19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=19
InvertMeasure=0

[MeasureFFT_R_20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=20
InvertMeasure=0

[MeasureFFT_R_21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=21
InvertMeasure=0

[MeasureFFT_R_22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=22
InvertMeasure=0

[MeasureFFT_R_23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutput
Channel=R
Type=Band
BandIdx=23
InvertMeasure=0
