[Metadata]
Skin name=DESKTOP VU-METER
Version=2.0
Information=SOUND LEVEL
Author=HiTBiT-PA
Website=http://hitbit-pa.deviantart.com/
License=Creative Commons Attribution-Noncommercial-Share Alike 3.0 License

[Variables]
vRMSGain=3
vRMSAttack=150
vRMSDecay=150
vRMSDelay=600
vPeakGain=2
vPeakAttack=150
vPeakDecay=1200
vFFTSize=4096
vFFTOverlap=2048
vFFTAttack=150
vFFTDecay=100
vFreqMin=20
vFreqMax=20000
vSensitivity=45
vColor=140,140,140
vAlpha=140
vPort=Output



vVUMeter=Bottom
vLeds=1
vSize=1
vAudio=Mono
vVUColor=Custom
vDelay=0
