[Acceso1]
Meter=Image
ImageName=#I1#
MeterStyle=IconStyle
TransformationMatrix=1;0;0;1;0;0
MouseOverAction=[!SetVariable m "1"][!SetOption "Titulo" "Text" "#NO1#"][!CommandMeasure CZ "Stop 2"][!CommandMeasure CZ "Execute 1"]
LeftMouseDownAction=["#R1#"]

[Acceso2]
Meter=Image
ImageName=#I2#
MeterStyle=IconStyle
TransformationMatrix=1;0;0;1;0;0
MouseOverAction=[!SetVariable m "2"][!SetOption "Titulo" "Text" "#NO2#"][!CommandMeasure CZ "Stop 2"][!CommandMeasure CZ "Execute 1"]
LeftMouseDownAction=["#R2#"]

[Acceso3]
Meter=Image
ImageName=#I3#
MeterStyle=IconStyle
TransformationMatrix=1;0;0;1;0;0
MouseOverAction=[!SetVariable m "3"][!SetOption "Titulo" "Text" "#NO3#"][!CommandMeasure CZ "Stop 2"][!CommandMeasure CZ "Execute 1"]
LeftMouseDownAction=["#R3#"]

[Acceso4]
Meter=Image
ImageName=#I4#
MeterStyle=IconStyle
TransformationMatrix=1;0;0;1;0;0
MouseOverAction=[!SetVariable m "4"][!SetOption "Titulo" "Text" "#NO4#"][!CommandMeasure CZ "Stop 2"][!CommandMeasure CZ "Execute 1"]
LeftMouseDownAction=["#R4#"]
